name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    
    env:
      Server_Build_Path: EtcordSharp.Server\bin\Release\netcoreapp3.0
      Client_Build_Path: EtcordSharp.Client.Windows\bin\Release\netcoreapp3.0

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Upload server build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Server Build
        path: ${{ env.Server_Build_Path }}
        
    - name: Upload client build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Client Build
        path: ${{ env.Client_Build_Path }}

